name: compile

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: gcc hello.c -o a.out
      run: a.out
